Upgraded buildTools version, gradle wrapper version, disabled com.nee…
Glucosio/glucosio-android pull request #379
Opened 2017-11-25 14:11 UTC by rcd27

…nbedankt.android-apt for AndroidStudio v3.x

2017-11-25 21:03 UTC, emartynov requested changes
Thanks for the contribution! Could you react to comments?

2017-11-25 21:03 UTC, emartynov commented on build.gradle
> +    ext.buildToolsVer = '26.0.2'
26.0.3?

2017-11-25 21:03 UTC, emartynov commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:3.0.1'
You should use `google()` repository for this dependency. They don't distribute through the jcenter anymore.

2017-11-25 21:03 UTC, emartynov commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
4.3.1?

2017-11-27 07:53 UTC, piotrek1543 commented on .travis.yml
>      - android-25
Should be `android-27`

2017-11-27 07:55 UTC, ghost reviewed
In `.travis.yml` you forgot to change `android-25` to `android-27`. Please fix it

2017-11-27 09:59 UTC, closed without merging